[colors]

# Normal
foreground = '#ebdbb2'
background = '#1d2021'
black      = '#1d2021'
blue       = '#458588'
cursor     = '#ebdbb2'
cyan       = '#689d6a'
green      = '#98971a'
magenta    = '#b16286'
red        = '#cc241d'
white      = '#a89984'
yellow     = '#d79921'

# UI colors
tabs                   = '#1d2021'
tabs-foreground        = '#ebdbb2'
tabs-active            = '#98971a'
tabs-active-highlight  = '#98971a'
tabs-active-foreground = '#1d2021'
selection-foreground   = '#ebdbb2'
selection-background   = '#3c3836'

# Dim colors
dim-black      = '#928374'
dim-blue       = '#458588'
dim-cyan       = '#689d6a'
dim-foreground = '#a89984'
dim-green      = '#98971a'
dim-magenta    = '#b16286'
dim-red        = '#cc241d'
dim-white      = '#a89984'
dim-yellow     = '#d79921'

# Light colors
light-black      = '#928374'
light-blue       = '#83a598'
light-cyan       = '#8ec07c'
light-foreground = '#ebdbb2'
light-green      = '#b8bb26'
light-magenta    = '#d3869b'
light-red        = '#fb4934'
light-white      = '#ebdbb2'
light-yellow     = '#fabd2f'
